INSERT INTO COMPANY(name) VALUES('Azul');
INSERT INTO COMPANY(name) VALUES('Latam');
INSERT INTO COMPANY(name) VALUES('Gol');
INSERT INTO COMPANY(name) VALUES('Tap Air Portugal');
INSERT INTO COMPANY(name) VALUES('Copa Airlines');